// <auto-generated />
namespace ComplaintsManagement.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CostumersentityrenamedtoCustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CostumersentityrenamedtoCustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "202102141518289_Costumers entity renamed to Customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
