// <auto-generated />
namespace ComplaintsManagement.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class servicerateentityadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servicerateentityadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202104171901199_servicerate entity added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
